const USER_ACTIONS = {
  LOAD_ORGANISATIONS: "LOAD_ORGANISATIONS",
  LOAD_ORGANISATION: "LOAD_ORGANISATION",
  CREATE_ORGANISATION: "CREATE_ORGANISATION",
  UPDATE_ORGANISATION: "UPDATE_ORGANISATION",
  DELETE_ORGANISATION: "DELETE_ORGANISATION",

  LOAD_USERS: "LOAD_USERS",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  REMOVE_USER: "REMOVE_USER",

  LOAD_LICENSES: "LOAD_LICENSES",
  UPDATE_LICENSE: "UPDATE_LICENSE",

  LOAD_BILLING: "LOAD_BILLING",
  INITIATE_BILLING_SESSION: "INITIATE_BILLING_SESSION",
  UPDATE_PAYMENT_METHOD: "UPDATE_PAYMENT_METHOD",

  LOAD_SETTINGS: "LOAD_SETTINGS",
  UPDATE_SETTINGS: "UPDATE_SETTINGS",
};

export default USER_ACTIONS;
