const buDashBoard = {
  riskOverTheYear: {
    hardware: {
      risks: [0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 1],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
    software: {
      risks: [0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
    people: {
      risks: [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
    premises: {
      risks: [0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
    organizational: {
      risks: [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
    clinical: {
      risks: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
  },
  risksByStatus: {
    open: {
      risks: [0, 6, 0, 0, 0, 2],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
    mitigated: {
      risks: [2, 2, 0, 0, 5, 1],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
    accepted: {
      risks: [0, 0, 0, 0, 0, 0],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
    escalated: {
      risks: [0, 1, 0, 0, 0, 0],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
  },
  risksOverview: {
    totalRisksInThisSystemDates: 18,
    totalOpenedRisksInThisMonth: 8,
    totalMitigatedRisksInThisMonth: 10,
    totalEscalatedRisksInThisMonth: 1,
    totalAcceptedRisksInThisMonth: 0,
  },
  finance: {
    costs: [500, 82, 0, 0, 0],
    areas: ["Hardware", "Software", "People", "Premises", "Information"],
  },
  inventory: {
    amounts: [16, 8, 2, 1, 16],
    areas: ["Hardware", "Software", "People", "Premises", "Information"],
  },
  audits: {
    findings: {
      data: [3, 10, 60],
      areas: ["Risks", "OFIs", "Non conformities"],
    },
    completed: 0,
    inCompleted: 0,
  },
  incidentsByStatus: {
    open: {
      incidents: [0, 0, 0, 0, 0, 0],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
    resolved: {
      incidents: [12, 5, 3, 0, 2, 0],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
    escalated: {
      incidents: [0, 1, 0, 0, 1, 0],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
  },
  incidents: {
    p1AvgResolutionTime: {
      time: "13hr :50min",
      alert: true,
    },
    p2AvgResolutionTime: {
      time: "10hr :35min",
      alert: false,
    },
    p3AvgResolutionTime: {
      time: "06hr :54min",
      alert: false,
    },
    p4AvgResolutionTime: {
      time: "13hr :33min",
      alert: false,
    },
    total: 25,
    resolved: 25,
  },
  improvementsByStatus: {
    open: {
      improvements: [8, 1, 0, 0, 1, 0],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
    implemented: {
      improvements: [0, 1, 0, 2, 2, 0],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
  },
  supplierCompliance: {
    compliant: 0,
    inCompliant: 8,
    percentage: 0,
  },
  supplierIncidents: {
    open: 0,
    resolved: 0,
  },
  compliance: {
    iso27001: 100,
    iso27001_2022: 0,
    iso27001_2022_annex_a: 45,
    iso27002: 1,
    iso9001: 0,
    iso45001: null,
    iso14001: 0,
    iso20000: 0,
    dsptNhs: 0,
    bs9997: null,
    iso15686_5: null,
  },
  crm: {
    customers: {
      stages: ["Qualified", "Live", "Proposal", "Prospect"],
      counts: [4, 2, 1, 7],
    },
    contractValue: {
      stages: ["Qualified", "Live", "Proposal", "Prospect"],
      amounts: [8400, 2580, 750000, 5000],
    },
    invoiceThisMonth: {
      status: [],
      counts: [],
    },
    invoiceAmountThisMonth: {
      status: [],
      amounts: [],
    },
    mostValuedLiveCustomer: {
      name: "Pactivate Ltd",
      value: 2580,
    },
    totalLiveContractValue: 2580,
    averageContractValue: 1290,
    lessValuedLiveCustomer: {
      name: "ADDVantage Technologies ",
      value: 0,
    },
    activeCampaign: 0,
    closedCampaign: 0,
    monthlyCampaign: [],
  },
  supplier: {
    contractValue: {
      total: 4776,
    },
  },
  digitalMaturityMatrix: {
    riskManagement: {
      label: "Risk management",
      point: 3,
      percentage: 37,
    },
    incidentManagement: {
      label: "Incident management",
      point: 3,
      percentage: 62,
    },
    supplierManagement: {
      label: "Supplier management",
      point: 3,
      percentage: 50,
    },
    documentManagement: {
      label: "Document management",
      point: 3,
      percentage: 50,
    },
    cip: {
      label: "CIP",
      point: 3,
      percentage: 75,
    },
    audits: {
      label: "Audits",
      point: 2,
      percentage: 0,
    },
    inventory: {
      label: "Inventory",
      point: 3,
      percentage: 37,
    },
  },
  systemDate: {
    start: "2021-06-20T18:00:00.000Z",
    end: "2022-07-20T18:00:00.000Z",
  },
  groupName: "iMS Systems",
  numberOfStaffs: 6,
  staffRemote: 3,
  premises: 1,
  organizationalState: "Vulnerable",
  organizationalConfidence: 100,
  criticalArea: "Software",
  lastManagementReviewDate: null,
  nextManagementReviewDate: null,
  reference: "GDB-1",
  _id: "61b139de0b2a670daa2c434c",
  group: "61b139de0b2a670daa2c434b",
  createdAt: "2021-12-08T23:03:58.812Z",
  updatedAt: "2022-06-24T14:35:01.991Z",
  ID: 1,
  __v: 0,
  idPrefix: "GDB",
};
buDashBoard.risksOverview.totalEscalatedRisksInThisMonth;
exports.buDashBoard = buDashBoard;
