# Use an official Node.js runtime as the base image
FROM node:lts-hydrogen

# Set the working directory inside the container
WORKDIR /usr/src/app


# Copy the .npmrc file into the container
COPY .npmrc ./


# Copy package.json and package-lock.json to the container
COPY package.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port that the app will run on
EXPOSE 8000
EXPOSE 27017

# Set a build argument for the operating system
ARG OS

# Start the Node.js application
CMD ["npm", "run", "start:staging"]

