let moduleTypes = {
  _: "",
  tasks: "tasks",
  leaves: "leaves",
  risks: "risks",
  documentrepositories: "documentrepositories",
  documenttrees: "documenttrees",
  cqcsafeguardings: "cqcsafeguardings",
  customers: "customers",
  cqcdetails: "cqcdetails",
  controlstatuses: "controlstatuses",
  compliancecontrols: "compliancecontrols",
  managementreviews: "managementreviews",
  licenserequests: "licenserequests",
  cqcwhistleblows: "cqcwhistleblows",
  invoices: "invoices",
  activities: "activities",
  cqcsignificantevents: "cqcsignificantevents",
  audits: "audits",
  suppliers: "suppliers",
  incidents: "incidents",
  kpiobjectives: "kpiobjectives",
  cips: "cips",
  groups: "groups",
  complaints: "complaints",
  expensereports: "expensereports",
  documenttrees: "documenttrees",
  notifications: "notifications",
  cqcoverviews: "cqcoverviews",
  imsprojects: "imsprojects",
  cccalculations: "cccalculations",
  cccarbonreductioninitiatives: "cccarbonreductioninitiatives",
  imsprojectworkpackages: "imsprojectworkpackages",
};
module.exports = { moduleTypes };
