exports.IMS_SERVICES = {
  DASHBOARD: "Dashboard",
  OUR_IMS: "Our iMS",
  ORGANISATION: "Organisation",
  IAM_GROUPS: "Business units",
  IAM_PREMISES: "Premises",
  IAM_ROLES: "Roles",
  IAM_ACCESS_POLICIES: "Access policies",
  INVENTORY: "Inventory",
  INVITATIONS: "Invitation",
  MEMBERSHIPS: "Membership",
  PARTNERSHIPS: "Partnership",
  RISK_MANAGEMENT: "Risk management",
  INCIDENT_MANAGEMENT: "Incident management",
  AUDIT: "Audit",
  MANAGEMENT_REVIEW: "Management review",
  KPI_OBJECTIVE: "Kpi/Objectives",
  CONTINUAL_IMPROVEMENT_PLAN: "Continual improvement plan",
  COMPLIANCE_TOOL: "Compliance toolkits",
  SUPPLIER_MANAGEMENT: "Supplier management",
  DOCUMENT_MANAGEMENT: "Document management",
  TASK_MANAGER: "Task manager",
  CALENDAR: "Calendar",
  PROJECT_MANAGEMENT: "Project management",
  USERS: "Users",
  NOTIFICATIONS: "Notifications",
  LICENSE_MANAGEMENT: "License management",
  SYSTEM_DEFAULTS: "System configuration",
  CQC: "CQC",
  CRM: "CRM",
  ISO20000: "ISO 20000",
  ISO27001: "ISO 27001",
  ISO27001_2022: "ISO 27001 (2022)",
  ISO27001_2022_ANNEX_A: "ISO 27001 (2022 Annex A)",
  ISO27002: "ISO 27002",
  ISO9001: "ISO 9001",
  ISO45001: "ISO 45001",
  ISO14001: "ISO 14001",
  ISO15686_5: "ISO 15686-5",
  ESG_GOVERNANCE: "ESG Toolkit - Governance",
  ESG_SOCIAL: "ESG Toolkit - Social",
  ESG_ENVIRONMENTAL: "ESG Toolkit - Environmental",
  DSPTNHS: "DSPT",
  BS9997: "BS 9997",
};

exports.CUSTOMIZABLE_SERVICES = {
  INVENTORY: "Inventory",
  RISK_MANAGEMENT: "Risk management",
  INCIDENT_MANAGEMENT: "Incident management",
  MANAGEMENT_REVIEW: "Management review",
  KPI_OBJECTIVE: "Kpi/Objectives",
  CONTINUAL_IMPROVEMENT_PLAN: "Continual improvement plan",
  SUPPLIER_MANAGEMENT: "Supplier management",
  DOCUMENT_MANAGEMENT: "Document management",
  TASK_MANAGER: "Task manager",
  CALENDAR: "Calendar",
  CRM: "CRM",
};
