exports.dashBoard = {
  riskOverTheYear: {
    hardware: {
      risks: [0, 0, 0, 0, 0, 0, 16, 2, 2, 0, 2, 0],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
    software: {
      risks: [0, 0, 0, 0, 0, 0, 9, 0, 2, 0, 1, 0],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
    people: {
      risks: [0, 0, 0, 0, 0, 0, 10, 4, 2, 0, 0, 0],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
    premises: {
      risks: [0, 0, 0, 0, 0, 0, 5, 10, 1, 0, 0, 0],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
    organizational: {
      risks: [0, 0, 0, 0, 0, 0, 4, 4, 3, 1, 2, 0],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
    clinical: {
      risks: [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      months: [
        "JUL",
        "AUG",
        "SEP",
        "OCT",
        "NOV",
        "DEC",
        "JAN",
        "FEB",
        "MAR",
        "APR",
        "MAY",
        "JUN",
      ],
    },
  },
  risksByStatus: {
    open: {
      risks: [26, 12, 9, 1, 4, 0],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
    closed: {
      risks: [18, 9, 2, 0, 1, 0],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
    accepted: {
      risks: [2, 0, 0, 0, 1, 0],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
    escalated: {
      risks: [14, 18, 8, 4, 4, 0],
      months: ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"],
    },
  },
  businessFunctionsHavingMostRisks: {
    risks: [2, 35, 3, 0, 34, 8, 0, 0],
    businessFunctionNames: [
      "BMTrada",
      "Clive Lane Practice",
      "Executive Team",
      "GB Team",
      "Hollinwood Medical Practice",
      "MediSupplies",
      "Risk Management Group",
      "iMS Admin",
    ],
  },
  finance: {
    costs: [6495, 14725, 85000, 310000, 2650],
    areas: ["Hardware", "Software", "People", "Premises", "Information"],
  },
  inventory: {
    amounts: [24, 12, 8, 4, 16],
    areas: ["Hardware", "Software", "People", "Premises", "Information"],
  },
  nonConformities: {
    amount: [6, 3, 1, 1, 0, 0, 0, 0],
    businessFunctionNames: [
      "Clive Lane Practice",
      "Hollinwood Medical Practice",
      "MediSupplies",
      "Executive Team",
      "GB Team",
      "Risk Management Group",
      "BMTrada",
      "iMS Admin",
    ],
  },
  audits: {
    completed: 11,
    inCompleted: 13,
  },
  businessFunctionsWithMostOpportunities: {
    amount: [1, 7, 2, 1, 8, 2, 0, 0],
    businessFunctionNames: [
      "BMTrada",
      "Clive Lane Practice",
      "Executive Team",
      "GB Team",
      "Hollinwood Medical Practice",
      "MediSupplies",
      "Risk Management Group",
      "iMS Admin",
    ],
  },
  businessFunctionsWithMostImprovements: {
    amount: [0, 3, 1, 0, 4, 1, 0, 0],
    businessFunctionNames: [
      "BMTrada",
      "Clive Lane Practice",
      "Executive Team",
      "GB Team",
      "Hollinwood Medical Practice",
      "MediSupplies",
      "Risk Management Group",
      "iMS Admin",
    ],
  },
  businessFunctionsWithMostIncidents: {
    total: [2, 4, 3, 1, 9, 7, 0, 0],
    resolved: [2, 4, 1, 0, 6, 1, 0, 0],
    businessFunctionNames: [
      "BMTrada",
      "Clive Lane Practice",
      "Executive Team",
      "GB Team",
      "Hollinwood Medical Practice",
      "MediSupplies",
      "Risk Management Group",
      "iMS Admin",
    ],
  },
  incidents: {
    p1AvgResolutionTime: {
      time: "00hr :01min",
      alert: false,
    },
    p2AvgResolutionTime: {
      time: "23hr :15min",
      alert: true,
    },
    p3AvgResolutionTime: {
      time: "21hr :39min",
      alert: false,
    },
    p4AvgResolutionTime: {
      time: "00hr :01min",
      alert: false,
    },
    total: 26,
    resolved: 14,
  },
  supplier: {
    contractValue: {
      total: 888024,
    },
  },
  supplierCompliance: {
    compliant: 3,
    inCompliant: 3,
    percentage: 50,
  },
  supplierIncidents: {
    open: 4,
    resolved: 2,
  },
  compliance: {
    iso27001: 29,
    iso27001_2022: 34,
    iso27001_2022_annex_a: 40,
    iso27002: 11,
    iso9001: 3,
    iso45001: 3,
    iso14001: 22,
    dsptNhs: 6,
    iso20000: 12,
    bs9997: 32,
  },
  cqc: {
    compliance: {
      overall: [
        {
          siteName: {
            shortName: "Clive Lane Practice",
            fullName: "Clive Lane Practice",
          },
          percentage: 4,
          _id: "629764474e471c2591bd0512",
          rating: "Inadequate",
        },
        {
          siteName: {
            shortName: "Hollinwood Medical Practice",
            fullName: "Hollinwood Medical Practice",
          },
          percentage: 43,
          _id: "629764474e471c2591bd0513",
          rating: "Good",
        },
        {
          siteName: {
            shortName: "MediSupplies",
            fullName: "MediSupplies",
          },
          percentage: 0,
          _id: "629764474e471c2591bd0514",
          rating: "Not rated",
        },
      ],
    },
    significantEvents: {
      total: [3, 1, 0],
      signedOff: [0, 1, 0],
      businessFunctionNames: [
        {
          _id: "629764474e471c2591bd050f",
          shortName: "Clive Lane Practice",
          fullName: "Clive Lane Practice",
        },
        {
          _id: "629764474e471c2591bd0510",
          shortName: "Hollinwood Medical Practice",
          fullName: "Hollinwood Medical Practice",
        },
        {
          _id: "629764474e471c2591bd0511",
          shortName: "MediSupplies",
          fullName: "MediSupplies",
        },
      ],
    },
    whistleBlows: {
      total: [1, 5, 0],
      signedOff: [1, 2, 0],
      businessFunctionNames: [
        {
          _id: "629764474e471c2591bd050c",
          shortName: "Clive Lane Practice",
          fullName: "Clive Lane Practice",
        },
        {
          _id: "629764474e471c2591bd050d",
          shortName: "Hollinwood Medical Practice",
          fullName: "Hollinwood Medical Practice",
        },
        {
          _id: "629764474e471c2591bd050e",
          shortName: "MediSupplies",
          fullName: "MediSupplies",
        },
      ],
    },
    complaints: {
      total: [0, 1, 0],
      signedOff: [1, 1, 0],
      businessFunctionNames: [
        {
          _id: "629764474e471c2591bd0509",
          shortName: "Clive Lane Practice",
          fullName: "Clive Lane Practice",
        },
        {
          _id: "629764474e471c2591bd050a",
          shortName: "Hollinwood Medical Practice",
          fullName: "Hollinwood Medical Practice",
        },
        {
          _id: "629764474e471c2591bd050b",
          shortName: "MediSupplies",
          fullName: "MediSupplies",
        },
      ],
    },
    safeGuardings: {
      total: [0, 2, 0],
      signedOff: [1, 1, 0],
      businessFunctionNames: [
        {
          _id: "629764474e471c2591bd0506",
          shortName: "Clive Lane Practice",
          fullName: "Clive Lane Practice",
        },
        {
          _id: "629764474e471c2591bd0507",
          shortName: "Hollinwood Medical Practice",
          fullName: "Hollinwood Medical Practice",
        },
        {
          _id: "629764474e471c2591bd0508",
          shortName: "MediSupplies",
          fullName: "MediSupplies",
        },
      ],
    },
  },
  crm: {
    customers: {
      stages: ["Live", "Qualified", "Proposal", "Prospect", "Warm lead"],
      counts: [23, 27, 24, 40, 26],
    },
    contractValue: {
      stages: ["Live", "Qualified", "Proposal", "Prospect", "Warm lead"],
      amounts: [330901.8, 115859, 72854.97, 159216.07, 104534],
    },
    invoiceThisMonth: {
      status: [],
      counts: [],
    },
    invoiceAmountThisMonth: {
      status: [],
      amounts: [],
    },
    mostValuedLiveCustomer: {
      value: 200000,
      name: "Priory Group",
    },
    totalLiveContractValue: 330901.8,
    averageContractValue: 14387.034782608695,
    lessValuedLiveCustomer: {
      value: 0,
      name: "Oldham Greenhill CSRC",
    },
    activeCampaign: 1,
    closedCampaign: 0,
    monthlyCampaign: [
      {
        count: 1,
        _id: "MAY",
      },
    ],
  },
  digitalMaturityMatrix: {
    riskManagement: {
      label: "Risk management",
      point: 3,
      percentage: 3,
    },
    incidentManagement: {
      label: "Incident management",
      point: 3,
      percentage: 3,
    },
    supplierManagement: {
      label: "Supplier management",
      point: 3,
      percentage: 3,
    },
    documentManagement: {
      label: "Document management",
      point: 3,
      percentage: 3,
    },
    cip: {
      label: "CIP",
      point: 3,
      percentage: 0,
    },
    audits: {
      label: "Audits",
      point: 4,
      percentage: 4,
    },
    inventory: {
      label: "Inventory",
      point: 3,
      percentage: 3,
    },
  },
  systemDate: {
    start: "2022-01-01T00:00:00.000Z",
    end: "2022-06-21T00:00:00.000Z",
  },
  businessFunctions: 8,
  complianceFunctions: 3,
  numberOfStaffs: 21,
  staffRemote: 6,
  premises: 2,
  reference: "DB-0",
  idPrefix: "DB",
  _id: "61debb13dd4a172028ffc010",
  organizationId: "61debb11dd4a172028ffbfbc",
  createdAt: "2022-01-12T11:27:15.541Z",
  updatedAt: "2022-06-01T13:06:15.335Z",
  ID: 0,
  __v: 0,
  criticalArea: "Hardware",
  lastManagementReviewDate: "2022-05-19T08:00:00.000Z",
  nextManagementReviewDate: "2022-06-03T11:00:00.000Z",
  organizationalConfidence: 100,
  organizationalState: "Vulnerable",
};
